packages:
  - packages/**
  - playground
  - plugins/**
overrides:
  autoprefixer: ^10.4.20
  eslint: ^9.17.0
  postcss: ^8.5.3
  react: ^19.1.1
  react-dom: ^19.1.1
  typescript: ^5.7.3
  '@types/node': ^22.15.18
  '@types/react': ^19.1.4
  '@types/react-dom': ^19.1.5
  motia: link:packages/snap
